panelapp/api/urls.py
##
## Copyright (c) 2016-2019 Genomics England Ltd.
##
## This file is part of PanelApp
## (see https://panelapp.genomicsengland.co.uk).
##
## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
from django.conf import settings
from django.urls import (
    include,
    path,
)
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from .permissions import ReadOnlyPermissions

schema_view = get_schema_view(
    openapi.Info(
        title="PanelApp API",
        default_version=settings.REST_FRAMEWORK["DEFAULT_VERSION"],
        description="PanelApp API",
        terms_of_service="https://panelapp.genomicsengland.co.uk/policies/terms/",
        contact=openapi.Contact(email="panelapp@genomicsengland.co.uk"),
        license=openapi.License(name="MIT License"),
    ),
    patterns=["api"],
    validators=["flex", "ssv"],
    public=True,
    permission_classes=(ReadOnlyPermissions,),
)

app_name = "api"
urlpatterns = [path("v1/", include("api.v1.urls", namespace="v1"))]

panelapp/panelapp/urls.py
##
## Copyright (c) 2016-2019 Genomics England Ltd.
##
## This file is part of PanelApp
## (see https://panelapp.genomicsengland.co.uk).
##
## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
"""panelapp URL Configuration

"""
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import (
    path,
    re_path,
)
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from .autocomplete import (
    GeneAutocomplete,
    SimpleAllPanelsAutocomplete,
    SimplePanelTypesAutocomplete,
    SimplePublicPanelsAutocomplete,
    SourceAutocomplete,
    TagsAutocomplete,
)
from .health.views.health_check_views import (
    HealthCheck,
    ping,
)
from .views import (
    Homepage,
    VersionView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="PanelApp API",
        default_version="v1",
        description="PanelApp API",
        terms_of_service="https://panelapp.genomicsengland.co.uk/policies/terms/",
        contact=openapi.Contact(email="panelapp@genomicsengland.co.uk"),
    ),
    patterns=[path("api/", include("api.urls"))],  # exclude old webservices
    validators=["flex", "ssv"],
    public=True,
    permission_classes=(permissions.AllowAny,),  #  FIXME(Oleg) we need read only.
)


urlpatterns = [
    path("", Homepage.as_view(), name="home"),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("panels/", include("panels.urls", namespace="panels")),
    path("crowdsourcing/", include("v1rewrites.urls", namespace="v1rewrites")),
    re_path(
        r"^api/docs(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=None),
        name="schema-json",
    ),
    re_path(
        r"^api/docs/$",
        schema_view.with_ui("swagger", cache_timeout=None),
        name="schema-swagger-ui",
    ),
    path("api/", include("api.urls", namespace="api")),
    path("WebServices/", include("webservices.urls", namespace="webservices")),
    path("markdownx/", include("markdownx.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    path("autocomplete/gene/", GeneAutocomplete.as_view(), name="autocomplete-gene"),
    path(
        "autocomplete/source/", SourceAutocomplete.as_view(), name="autocomplete-source"
    ),
    path("autocomplete/tags/", TagsAutocomplete.as_view(), name="autocomplete-tags"),
    path(
        "autocomplete/panels/simple/",
        SimplePublicPanelsAutocomplete.as_view(),
        name="autocomplete-simple-panels-public",
    ),
    path(
        "autocomplete/panels/all/",
        SimpleAllPanelsAutocomplete.as_view(),
        name="autocomplete-simple-panels-all",
    ),
    path(
        "autocomplete/panels/type/",
        SimplePanelTypesAutocomplete.as_view(),
        name="autocomplete-simple-panel-types",
    ),
    path("version/", VersionView.as_view(), name="version"),
    path("health/1/", HealthCheck.as_view(), name="health-check"),
    path("ping/1/", ping, name="ping"),
]

if settings.DEBUG:
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
        ] + urlpatterns

    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panelapp/panels/urls.py
##
## Copyright (c) 2016-2019 Genomics England Ltd.
##
## This file is part of PanelApp
## (see https://panelapp.genomicsengland.co.uk).
##
## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
from django.conf.urls import url
from django.views.generic import RedirectView

from .ajax_views import (
    ApproveEntityAjaxView,
    ApprovePanelAjaxView,
    ClearModeOfPathogenicityAjaxView,
    ClearPhoenotypesAjaxView,
    ClearPublicationsAjaxView,
    ClearSingleSourceAjaxView,
    ClearSourcesAjaxView,
    ClearTranscriptAjaxView,
    DeleteEntityAjaxView,
    DeleteEntityCommentAjaxView,
    DeleteEntityEvaluationAjaxView,
    DeletePanelAjaxView,
    GetEntityCommentFormAjaxView,
    RejectPanelAjaxView,
    SubmitEntityCommentFormAjaxView,
    UpdateEntityMOIAjaxView,
    UpdateEntityMOPAjaxView,
    UpdateEntityPhenotypesAjaxView,
    UpdateEntityPublicationsAjaxView,
    UpdateEntityRatingAjaxView,
    UpdateEntityTagsAjaxView,
)
from .enums import VALID_ENTITY_FORMAT
from .views import (
    ActivityListView,
    AdminUploadGenesView,
    AdminUploadPanelsView,
    AdminUploadReviewsView,
    AdminView,
    CompareGeneView,
    ComparePanelsView,
    CopyReviewsView,
    CreatePanelView,
    DownloadAllGenes,
    DownloadAllPanels,
    DownloadAllRegions,
    DownloadAllSTRs,
    DownloadPanelTSVView,
    DownloadPanelVersionTSVView,
    EntitiesListView,
    EntityDetailView,
    EntityReviewView,
    GeneDetailRedirectView,
    GenePanelSpanshotView,
    GenePanelView,
    MarkEntityReadyView,
    MarkGeneNotReadyView,
    OldCodeURLRedirect,
    PanelAddEntityView,
    PanelEditEntityView,
    PanelMarkNotReadyView,
    PanelsIndexView,
    PromotePanelView,
    RedirectGenesToEntities,
    UpdatePanelView,
)

app_name = "panels"

entity_types = "gene|str|region"
TYPE_PARAM = f"(?P<entity_type>({entity_types}))"
NAME_PARAM = f"(?P<entity_name>{VALID_ENTITY_FORMAT})"
PK_PARAM = "(?P<pk>[0-9]+)"
COMMENT_PK_PARAM = "(?P<comment_pk>[0-9]+)"

urlpatterns = [
    url(r"^$", PanelsIndexView.as_view(), name="index"),
    url(r"^compare/$", ComparePanelsView.as_view(), name="compare_panels_form"),
    url(
        r"^compare/(?P<panel_1_id>[0-9]+)/(?P<panel_2_id>[0-9]+)$",
        ComparePanelsView.as_view(),
        name="compare",
    ),
    url(
        r"^compare/(?P<panel_1_id>[0-9]+)/(?P<panel_2_id>[0-9]+)/(?P<gene_symbol>[\w\-]+)$",
        CompareGeneView.as_view(),
        name="compare_genes",
    ),
    url(
        r"^copy/(?P<panel_1_id>[0-9]+)/(?P<panel_2_id>[0-9]+)$",
        CopyReviewsView.as_view(),
        name="copy_reviews",
    ),
    url(rf"^{PK_PARAM}/$", GenePanelView.as_view(), name="detail"),
    url(rf"^{PK_PARAM}/update$", UpdatePanelView.as_view(), name="update"),
    url(rf"^{PK_PARAM}/promote$", PromotePanelView.as_view(), name="promote"),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/add$",
        PanelAddEntityView.as_view(),
        name="add_entity",
    ),
    url(rf"^{PK_PARAM}/delete$", DeletePanelAjaxView.as_view(), name="delete_panel"),
    url(rf"^{PK_PARAM}/reject$", RejectPanelAjaxView.as_view(), name="reject_panel"),
    url(
        rf"^{PK_PARAM}/approve$",
        ApprovePanelAjaxView.as_view(),
        name="approve_panel",
    ),
    url(
        rf"^{PK_PARAM}/download/(?P<categories>[0-4]+)/$",
        DownloadPanelTSVView.as_view(),
        name="download_panel_tsv",
    ),
    url(
        rf"^{PK_PARAM}/download_version/$",
        DownloadPanelVersionTSVView.as_view(),
        name="download_old_panel_tsv",
    ),
    url(
        rf"^{PK_PARAM}/{NAME_PARAM}/$",
        RedirectGenesToEntities.as_view(),
        name="redirect_previous_structure",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/$",
        GenePanelSpanshotView.as_view(),
        name="evaluation",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/edit$",
        PanelEditEntityView.as_view(),
        name="edit_entity",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/review$",
        EntityReviewView.as_view(),
        name="review_entity",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/mark_as_ready$",
        MarkEntityReadyView.as_view(),
        name="mark_entity_as_ready",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/mark_as_not_ready$",
        MarkGeneNotReadyView.as_view(),
        name="mark_entity_as_not_ready",
    ),
    # AJAX endpoints
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/delete$",
        DeleteEntityAjaxView.as_view(),
        name="delete_entity",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/approve$",
        ApproveEntityAjaxView.as_view(),
        name="approve_entity",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_sources$",
        ClearSourcesAjaxView.as_view(),
        name="clear_entity_sources",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_source/(?P<source>(.*))/$",
        ClearSingleSourceAjaxView.as_view(),
        name="clear_entity_source",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_phenotypes$",
        ClearPhoenotypesAjaxView.as_view(),
        name="clear_entity_phenotypes",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_transcript$",
        ClearTranscriptAjaxView.as_view(),
        name="clear_entity_transcript",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_publications$",
        ClearPublicationsAjaxView.as_view(),
        name="clear_entity_publications",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_mode_of_pathogenicity$",
        ClearModeOfPathogenicityAjaxView.as_view(),
        name="clear_entity_mode_of_pathogenicity",
    ),
    # AJAX Review endpoints
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_tags/$",
        UpdateEntityTagsAjaxView.as_view(),
        name="update_entity_tags",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_rating/$",
        UpdateEntityRatingAjaxView.as_view(),
        name="update_entity_rating",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_moi/$",
        UpdateEntityMOIAjaxView.as_view(),
        name="update_entity_moi",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_mop/$",
        UpdateEntityMOPAjaxView.as_view(),
        name="update_entity_mop",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_phenotypes/$",
        UpdateEntityPhenotypesAjaxView.as_view(),
        name="update_entity_phenotypes",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_publications/$",
        UpdateEntityPublicationsAjaxView.as_view(),
        name="update_entity_publications",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/delete_evaluation/(?P<evaluation_pk>[0-9]+)/$",
        DeleteEntityEvaluationAjaxView.as_view(),
        name="delete_evaluation_by_user",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/edit_comment/{COMMENT_PK_PARAM}/$",
        GetEntityCommentFormAjaxView.as_view(),
        name="edit_comment_by_user",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/submit_edit_comment/{COMMENT_PK_PARAM}/$",
        SubmitEntityCommentFormAjaxView.as_view(),
        name="submit_edit_comment_by_user",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/delete_comment/{COMMENT_PK_PARAM}/$",
        DeleteEntityCommentAjaxView.as_view(),
        name="delete_comment_by_user",
    ),
    url(
        rf"^{PK_PARAM}/mark_not_ready$",
        PanelMarkNotReadyView.as_view(),
        name="mark_not_ready",
    ),
    url(
        r"^(?P<pk>[a-z0-9]{24})/(?P<uri>.*|$)",
        OldCodeURLRedirect.as_view(),
        name="old_code_url_redirect",
    ),
    url(r"^create/", CreatePanelView.as_view(), name="create"),
    url(r"^entities/$", EntitiesListView.as_view(), name="entities_list"),
    url(r"^genes/$", RedirectView.as_view(url="/panels/entities"), name="genes_list"),
    url(
        rf"^entities/{NAME_PARAM}$",
        EntityDetailView.as_view(),
        name="entity_detail",
    ),
    url(
        rf"^genes/{NAME_PARAM}$",
        GeneDetailRedirectView.as_view(),
    ),
    url(r"^activity/$", ActivityListView.as_view(), name="activity"),
    url(r"^admin/", AdminView.as_view(), name="admin"),
    url(r"^upload_genes/", AdminUploadGenesView.as_view(), name="upload_genes"),
    url(r"^download_genes/", DownloadAllGenes.as_view(), name="download_genes"),
    url(r"^download_strs/", DownloadAllSTRs.as_view(), name="download_strs"),
    url(r"^download_regions/", DownloadAllRegions.as_view(), name="download_regions"),
    url(r"^upload_panel/", AdminUploadPanelsView.as_view(), name="upload_panels"),
    url(r"^download_panel/", DownloadAllPanels.as_view(), name="download_panels"),
    url(r"^upload_reviews/", AdminUploadReviewsView.as_view(), name="upload_reviews"),
]

panelapp/panelapp/health/views/health_check_views.py
import logging

from django.conf import settings
from django.http import JsonResponse
from rest_framework import permissions
from rest_framework.decorators import permission_classes
from rest_framework.views import APIView

from panelapp.health.enums import Status
from panelapp.health.health_check_serializers import HealthCheckSerializer
from panelapp.health.health_checks import checks as health_checks

LOGGER = logging.getLogger(__name__)


def ping(_):
    pong = {"ping": "pong"}
    return JsonResponse(pong)


def error(_):
    LOGGER.info("hello info", extra={"extra_item": "yes"})
    LOGGER.error("hello error", extra={"extra_item": "yes"})
    LOGGER.debug("hello debug", extra={"extra_item": "yes"})
    LOGGER.warn("hello warn", extra={"extra_item": "yes"})
    try:
        assert False
    except Exception as e:
        LOGGER.exception("exception message", exc_info=True)

    return JsonResponse({"error": "dummy error"}, status=500)


@permission_classes((permissions.AllowAny,))
class HealthCheck(APIView):
    serializer = HealthCheckSerializer

    def get(self, request):
        data = health_checks.to_dict(
            request.build_absolute_uri(),
            show_dependencies=self.display_extra,
            skip_resources=self.skip_resources,
        )
        result = self.serializer(data=data)

        if result.is_valid(raise_exception=True):
            if result.data["status"] == Status.DOWN.value:
                return JsonResponse(result.data, status=503)

            return JsonResponse(result.data)

    @property
    def display_extra(self):
        token = self.request.GET.get("token")
        return token and token == settings.HEALTH_CHECK_TOKEN

    @property
    def skip_resources(self):
        skip_resources = self.request.GET.get("skip")
        return skip_resources.lower().split(",") if skip_resources else []

panelapp/panelapp/templates/default.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js">
  <head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script>(function(d){d.className=d.className.replace(/^no-js\b/,'js');}(document.documentElement));</script>
    <link rel="stylesheet" href="{% static "bootstrap.min.css" %}" >
    <link rel="stylesheet" href="{% static "font-awesome-4.3.0/css/font-awesome.min.css" %}">
    <script src="{% static "jquery-1.10.2.min.js" %}"></script>
    {% block header %}{% endblock %}
    <link rel="stylesheet" href="{% static "panel_app.css" %}" >
    <title>{% block title %}PanelApp{% endblock %}</title>
  </head>
<body>
<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">PanelApp</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'panels:index' %}">Panels</a></li>
        <li><a href="{% url 'panels:entities_list' %}">Genes and Entities</a></li>
        <li><a href="{% url 'panels:activity' %}">Activity</a></li>
        {% if request.user.is_authenticated and request.user.reviewer.is_GEL %}
        <li><a href="{% url 'panels:create' %}">Add panel</a></li>
        <li><a href="{% url 'panels:admin' %}">Import panel</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Resources <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'panels:download_genes' %}">Download all genes</a></li>
            <li><a href="{% url 'panels:download_strs' %}">Download all STRs</a></li>
              <li><a href="{% url 'panels:download_regions' %}">Download all Regions</a></li>
            <li><a href="{% url 'panels:download_panels' %}">Download all panels</a></li>
          </ul>
        </li>
        {% endif %}
      </ul>

      {% if request.user.is_authenticated %}
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'accounts:profile' %}"><strong>{{ request.user }}</strong></a></li>
        <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
      </ul>
      {% elif use_cognito %}
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'accounts:login' %}">Log in</a></li>
      </ul>
      {% else %}
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Log in</a></li>
        <li><a href="{% url 'accounts:register' %}">Register</a></li>
      </ul>
      {% endif %}
    </div>
  </div>
</div>

<div class="container">
  {% if messages %}
    {% for message in messages %}
      <div class="add-bottom-margin alert alert-{% if message.tags %}{{ message.tags }}{% else %}info{% endif %}">{{ message }}</div>
    {% endfor %}
  {% endif %}
  {% block content %}{% endblock %}
</div>

{% block body %}{% endblock %}
{% block modals %}{% endblock %}
<script src="{% static "bootstrap.min.js" %}"></script>
<script src="{% static "panel_app.js" %}"></script>
{% block js %}{% endblock %}
</body>
</html>

panelapp/panelapp/templates/default_anonymous.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js">
  <head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script>(function(d){d.className=d.className.replace(/^no-js\b/,'js');}(document.documentElement));</script>
    <link rel="stylesheet" href="{% static "bootstrap.min.css" %}" >
    <link rel="stylesheet" href="{% static "font-awesome-4.3.0/css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "panel_app.css" %}" >
    <script src="{% static "jquery-1.10.2.min.js" %}"></script>
    {% block header %}{% endblock %}
    <title>{% block title %}PanelApp{% endblock %}</title>
  </head>
<body>
<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">PanelApp</a>
    </div>
  </div>
</div>

<div class="container">
  {% if messages %}
    {% for message in messages %}
      <div class="add-bottom-margin alert alert-{% if message.tags %}{{ message.tags }}{% else %}info{% endif %}">{{ message }}</div>
    {% endfor %}
  {% endif %}
  {% block content %}{% endblock %}
</div>

{% block body %}{% endblock %}
{% block modals %}{% endblock %}
{% block js %}{% endblock %}
</body>
</html>