panelapp/api/urls.py
##
## Copyright (c) 2016-2019 Genomics England Ltd.
##
## This file is part of PanelApp
## (see https://panelapp.genomicsengland.co.uk).
##
## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
from django.conf import settings
from django.urls import (
    include,
    path,
)
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from .permissions import ReadOnlyPermissions

schema_view = get_schema_view(
    openapi.Info(
        title="PanelApp API",
        default_version=settings.REST_FRAMEWORK["DEFAULT_VERSION"],
        description="PanelApp API",
        terms_of_service="https://panelapp.genomicsengland.co.uk/policies/terms/",
        contact=openapi.Contact(email="panelapp@genomicsengland.co.uk"),
        license=openapi.License(name="MIT License"),
    ),
    patterns=["api"],
    validators=["flex", "ssv"],
    public=True,
    permission_classes=(ReadOnlyPermissions,),
)

app_name = "api"
urlpatterns = [path("v1/", include("api.v1.urls", namespace="v1"))]

panelapp/panels/urls.py
##
## Copyright (c) 2016-2019 Genomics England Ltd.
##
## This file is part of PanelApp
## (see https://panelapp.genomicsengland.co.uk).
##
## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
from django.conf.urls import url
from django.views.generic import RedirectView

from .ajax_views import (
    ApproveEntityAjaxView,
    ApprovePanelAjaxView,
    ClearModeOfPathogenicityAjaxView,
    ClearPhoenotypesAjaxView,
    ClearPublicationsAjaxView,
    ClearSingleSourceAjaxView,
    ClearSourcesAjaxView,
    ClearTranscriptAjaxView,
    DeleteEntityAjaxView,
    DeleteEntityCommentAjaxView,
    DeleteEntityEvaluationAjaxView,
    DeletePanelAjaxView,
    GetEntityCommentFormAjaxView,
    RejectPanelAjaxView,
    SubmitEntityCommentFormAjaxView,
    UpdateEntityMOIAjaxView,
    UpdateEntityMOPAjaxView,
    UpdateEntityPhenotypesAjaxView,
    UpdateEntityPublicationsAjaxView,
    UpdateEntityRatingAjaxView,
    UpdateEntityTagsAjaxView,
)
from .enums import VALID_ENTITY_FORMAT
from .views import (
    ActivityListView,
    AdminUploadGenesView,
    AdminUploadPanelsView,
    AdminUploadReviewsView,
    AdminView,
    CompareGeneView,
    ComparePanelsView,
    CopyReviewsView,
    CreatePanelView,
    DownloadAllGenes,
    DownloadAllPanels,
    DownloadAllRegions,
    DownloadAllSTRs,
    DownloadPanelTSVView,
    DownloadPanelVersionTSVView,
    EntitiesListView,
    EntityDetailView,
    EntityReviewView,
    GeneDetailRedirectView,
    GenePanelSpanshotView,
    GenePanelView,
    MarkEntityReadyView,
    MarkGeneNotReadyView,
    OldCodeURLRedirect,
    PanelAddEntityView,
    PanelEditEntityView,
    PanelMarkNotReadyView,
    PanelsIndexView,
    PromotePanelView,
    RedirectGenesToEntities,
    UpdatePanelView,
)

app_name = "panels"

entity_types = "gene|str|region"
TYPE_PARAM = f"(?P<entity_type>({entity_types}))"
NAME_PARAM = f"(?P<entity_name>{VALID_ENTITY_FORMAT})"
PK_PARAM = "(?P<pk>[0-9]+)"
COMMENT_PK_PARAM = "(?P<comment_pk>[0-9]+)"

urlpatterns = [
    url(r"^$", PanelsIndexView.as_view(), name="index"),
    url(r"^compare/$", ComparePanelsView.as_view(), name="compare_panels_form"),
    url(
        r"^compare/(?P<panel_1_id>[0-9]+)/(?P<panel_2_id>[0-9]+)$",
        ComparePanelsView.as_view(),
        name="compare",
    ),
    url(
        r"^compare/(?P<panel_1_id>[0-9]+)/(?P<panel_2_id>[0-9]+)/(?P<gene_symbol>[\w\-]+)$",
        CompareGeneView.as_view(),
        name="compare_genes",
    ),
    url(
        r"^copy/(?P<panel_1_id>[0-9]+)/(?P<panel_2_id>[0-9]+)$",
        CopyReviewsView.as_view(),
        name="copy_reviews",
    ),
    url(rf"^{PK_PARAM}/$", GenePanelView.as_view(), name="detail"),
    url(rf"^{PK_PARAM}/update$", UpdatePanelView.as_view(), name="update"),
    url(rf"^{PK_PARAM}/promote$", PromotePanelView.as_view(), name="promote"),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/add$",
        PanelAddEntityView.as_view(),
        name="add_entity",
    ),
    url(rf"^{PK_PARAM}/delete$", DeletePanelAjaxView.as_view(), name="delete_panel"),
    url(rf"^{PK_PARAM}/reject$", RejectPanelAjaxView.as_view(), name="reject_panel"),
    url(
        rf"^{PK_PARAM}/approve$",
        ApprovePanelAjaxView.as_view(),
        name="approve_panel",
    ),
    url(
        rf"^{PK_PARAM}/download/(?P<categories>[0-4]+)/$",
        DownloadPanelTSVView.as_view(),
        name="download_panel_tsv",
    ),
    url(
        rf"^{PK_PARAM}/download_version/$",
        DownloadPanelVersionTSVView.as_view(),
        name="download_old_panel_tsv",
    ),
    url(
        rf"^{PK_PARAM}/{NAME_PARAM}/$",
        RedirectGenesToEntities.as_view(),
        name="redirect_previous_structure",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/$",
        GenePanelSpanshotView.as_view(),
        name="evaluation",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/edit$",
        PanelEditEntityView.as_view(),
        name="edit_entity",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/review$",
        EntityReviewView.as_view(),
        name="review_entity",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/mark_as_ready$",
        MarkEntityReadyView.as_view(),
        name="mark_entity_as_ready",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/mark_as_not_ready$",
        MarkGeneNotReadyView.as_view(),
        name="mark_entity_as_not_ready",
    ),
    # AJAX endpoints
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/delete$",
        DeleteEntityAjaxView.as_view(),
        name="delete_entity",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/approve$",
        ApproveEntityAjaxView.as_view(),
        name="approve_entity",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_sources$",
        ClearSourcesAjaxView.as_view(),
        name="clear_entity_sources",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_source/(?P<source>(.*))/$",
        ClearSingleSourceAjaxView.as_view(),
        name="clear_entity_source",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_phenotypes$",
        ClearPhoenotypesAjaxView.as_view(),
        name="clear_entity_phenotypes",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_transcript$",
        ClearTranscriptAjaxView.as_view(),
        name="clear_entity_transcript",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_publications$",
        ClearPublicationsAjaxView.as_view(),
        name="clear_entity_publications",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_mode_of_pathogenicity$",
        ClearModeOfPathogenicityAjaxView.as_view(),
        name="clear_entity_mode_of_pathogenicity",
    ),
    # AJAX Review endpoints
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_tags/$",
        UpdateEntityTagsAjaxView.as_view(),
        name="update_entity_tags",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_rating/$",
        UpdateEntityRatingAjaxView.as_view(),
        name="update_entity_rating",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_moi/$",
        UpdateEntityMOIAjaxView.as_view(),
        name="update_entity_moi",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_mop/$",
        UpdateEntityMOPAjaxView.as_view(),
        name="update_entity_mop",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_phenotypes/$",
        UpdateEntityPhenotypesAjaxView.as_view(),
        name="update_entity_phenotypes",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_publications/$",
        UpdateEntityPublicationsAjaxView.as_view(),
        name="update_entity_publications",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/delete_evaluation/(?P<evaluation_pk>[0-9]+)/$",
        DeleteEntityEvaluationAjaxView.as_view(),
        name="delete_evaluation_by_user",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/edit_comment/{COMMENT_PK_PARAM}/$",
        GetEntityCommentFormAjaxView.as_view(),
        name="edit_comment_by_user",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/submit_edit_comment/{COMMENT_PK_PARAM}/$",
        SubmitEntityCommentFormAjaxView.as_view(),
        name="submit_edit_comment_by_user",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/delete_comment/{COMMENT_PK_PARAM}/$",
        DeleteEntityCommentAjaxView.as_view(),
        name="delete_comment_by_user",
    ),
    url(
        rf"^{PK_PARAM}/mark_not_ready$",
        PanelMarkNotReadyView.as_view(),
        name="mark_not_ready",
    ),
    url(
        r"^(?P<pk>[a-z0-9]{24})/(?P<uri>.*|$)",
        OldCodeURLRedirect.as_view(),
        name="old_code_url_redirect",
    ),
    url(r"^create/", CreatePanelView.as_view(), name="create"),
    url(r"^entities/$", EntitiesListView.as_view(), name="entities_list"),
    url(r"^genes/$", RedirectView.as_view(url="/panels/entities"), name="genes_list"),
    url(
        rf"^entities/{NAME_PARAM}$",
        EntityDetailView.as_view(),
        name="entity_detail",
    ),
    url(
        rf"^genes/{NAME_PARAM}$",
        GeneDetailRedirectView.as_view(),
    ),
    url(r"^activity/$", ActivityListView.as_view(), name="activity"),
    url(r"^admin/", AdminView.as_view(), name="admin"),
    url(r"^upload_genes/", AdminUploadGenesView.as_view(), name="upload_genes"),
    url(r"^download_genes/", DownloadAllGenes.as_view(), name="download_genes"),
    url(r"^download_strs/", DownloadAllSTRs.as_view(), name="download_strs"),
    url(r"^download_regions/", DownloadAllRegions.as_view(), name="download_regions"),
    url(r"^upload_panel/", AdminUploadPanelsView.as_view(), name="upload_panels"),
    url(r"^download_panel/", DownloadAllPanels.as_view(), name="download_panels"),
    url(r"^upload_reviews/", AdminUploadReviewsView.as_view(), name="upload_reviews"),
]

panelapp/panels/models/Level4Title.py
##
## Copyright (c) 2016-2019 Genomics England Ltd.
##
## This file is part of PanelApp
## (see https://panelapp.genomicsengland.co.uk).
##
## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
from django.contrib.postgres.fields import ArrayField
from django.db import models


class Level4Title(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    level3title = models.CharField(max_length=255)
    level2title = models.CharField(max_length=255)
    omim = ArrayField(models.CharField(max_length=255))
    orphanet = ArrayField(models.CharField(max_length=255))
    hpo = ArrayField(models.CharField(max_length=255))

    def __str__(self):
        return str(self.name)

    __hash__ = models.Model.__hash__

    def __eq__(self, other):
        if other == self.name:
            return True
        else:
            return False

    def dict_tr(self):
        return {
            "name": self.name,
            "description": self.description,
            "level3title": self.level3title,
            "level2title": self.level2title,
            "omim": self.omim,
            "orphanet": self.orphanet,
            "hpo": self.hpo,
        }

panelapp/panels/models/activity.py
##
## Copyright (c) 2016-2019 Genomics England Ltd.
##
## This file is part of PanelApp
## (see https://panelapp.genomicsengland.co.uk).
##
## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
from copy import deepcopy

from django.contrib.postgres.fields import JSONField
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
from django.db.models import Q
from model_utils.models import TimeStampedModel

from accounts.models import User

from .genepanel import GenePanel


class ActivityManager(models.Manager):
    def visible_to_public(self):
        """Return activities for all publicly visible panels"""

        qs = self.get_queryset()
        qs = qs.filter(
            Q(panel__status=GenePanel.STATUS.public)
            | Q(panel__status=GenePanel.STATUS.promoted)
        )
        return qs

    def visible_to_gel(self):
        """Return activities visible to GeL curators"""

        return self.get_queryset()


class Activity(TimeStampedModel):
    class Meta:
        ordering = ("-created",)

    objects = ActivityManager()

    panel = models.ForeignKey(GenePanel, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    text = models.TextField()
    item_type = models.CharField(max_length=32, null=True)  # TODO (Oleg) change to Enum
    entity_type = models.CharField(max_length=32, null=True)
    entity_name = models.CharField(max_length=128, null=True)
    extra_data = JSONField(default=dict, encoder=DjangoJSONEncoder)

    @property
    def panel_version(self):
        return self.extra_data.get("panel_version")

    @property
    def panel_name(self):
        return self.extra_data.get("panel_name")

    @property
    def user_name(self):
        return self.extra_data.get("user_name")

    @classmethod
    def log(cls, user, panel_snapshot, text, extra_info):
        extra_data = deepcopy(extra_info)

        if user:
            extra_data["user_name"] = user.get_full_name()

        extra_data["panel_name"] = panel_snapshot.panel.name
        extra_data["panel_id"] = panel_snapshot.panel_id
        extra_data["panel_version"] = panel_snapshot.version

        if "entity_type" in extra_info:
            extra_data["item_type"] = "entity"
            extra_data["entity_type"] = extra_info["entity_type"]
            extra_data["entity_name"] = extra_info["entity_name"]
        else:
            extra_data["item_type"] = "panel"

        cls.objects.create(
            user=user,
            panel=panel_snapshot.panel,
            text=text,
            extra_data=extra_data,
            item_type=extra_data["item_type"],
            entity_type=extra_data.get("entity_type"),
            entity_name=extra_data.get("entity_name"),
        )

panelapp/panels/templates/panels/genepanel_create.html
{% extends "default.html" %}
{% load bootstrap3 %}

{% block body %}
<div class="container">
    <div class="page-header" id="banner">
      <h1>{% block title %}Panel Creation{% endblock %}</h1>
    </div>

    <div class="well">
      <form class="" action="{% if object %}{% url "panels:update" object.panel.pk %}{% else %}{% url "panels:create" %}{% endif %}" method="post">{% csrf_token %}
        <legend>Panel Creation Tool</legend>
        {% bootstrap_form form %}

        <div>
          <button type="reset" class="btn btn-default">Cancel</button>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
      {{ form.media }}
    </div>
</div>
{% endblock %}

panelapp/panels/templates/panels/genepanel_detail.html
{% extends "default.html" %}
{% load staticfiles %}
{% load bootstrap3 panel_helpers %}
{% block header %}
<script src="{% static 'django_ajax/js/jquery.ajax.min.js' %}"></script>
<script src="{% static 'django_ajax/js/jquery.ajax-plugin.min.js' %}"></script>
{% endblock %}

{% block body %}
<div class="container">
  <ol class="breadcrumb">
      <li>
          <a href="{% url 'panels:index' %}">Panels</a>
      </li>
      <li class="active">
          {{ panel.level4title.name }}
      </li>
  </ol>

  {% if not panel.panel.is_public %}
  <div class="alert alert-danger" role="alert">This Panel is marked as {{ panel.panel.status|title }}</div>
  {% endif %}

    {% with signed_off_panel=signed_off %}
    {% if signed_off_panel %}
        <div class="alert alert-info" role="alert"><strong>{% signed_off_panel_message signed_off_panel %}</strong></div>
    {% endif %}
    {% endwith %}

  <div id="banner">
      <h1>
          {% block title %}{{ panel.level4title.name }} (Version {{ panel.major_version}}.{{ panel.minor_version}}){% endblock %}
      </h1>
      <div class="lead" id="panel_metadata">
          {% if panel.level4title.level3title %}
              Level 3: {{ panel.level4title.level3title }}<br />
          {% endif %}
          {% if panel.level4title.level2title %}
              Level 2: {{ panel.level4title.level2title }}<br />
          {% endif %}
          {% if panel.old_panels and panel.old_panels.0 %}
              <br/>Relevant disorders: {{ panel.old_panels|join:", " }}
          {% endif %}
          {% if panel.is_super_panel %}
              <br />This panel contains these {{ panel.child_panels.all|length }} panels:
              {% for child_panel in panel.child_panels.all %}<br /><a href="{% url 'panels:detail' child_panel.panel.pk %}">{{ child_panel }}</a> {% endfor %}
          {% endif %}
          {% if panel.panel.types.all %}
              <br />Panel types: {% for type in panel.panel.types.all %}{{ type.name }}{% if not forloop.last %}, {% endif %}{% endfor %}
          {% endif %}
          {% if signed_off %}
              <br />Latest signed off version: {% signed_off_version panel_id=panel.panel_id major_version=signed_off.major_version minor_version=signed_off.minor_version %} ({{ signed_off.signed_off_date }})
              <br />
              <form action="{% url 'panels:download_old_panel_tsv' panel.panel.id %}" id="header_download_signedoff" method="post">{% csrf_token %}
                  <input type="hidden" value="{{ signed_off.major_version }}.{{ signed_off.minor_version }}" name="panel_version" class="input form-control">
                  <button type="submit" class="btn btn-primary">Download Latest Signed-Off Version</button>
              </form>
              {% if signed_off_previous_versions %}Previously signed off versions: {% for major_version, minor_version in signed_off_previous_versions %}{% signed_off_version panel_id=panel.panel_id major_version=major_version minor_version=minor_version %}{% if not forloop.last %}, {% endif %}{% endfor %}{% endif %}
          {% endif %}

          {% if panel.panel.old_pk %}<br />Previous code: {{ panel.panel.old_pk }}{% endif %}
      </div>
  </div>

  <div class="row">
      <div class="col-md-8" id="panel_info">
          {% include "panels/genepanel_info.html" %}
      </div>
      <div class="col-md-4">
          {% if not panel.is_super_panel and contributors %}
              <h3 class="remove-top-margin add-bottom-margin">{{ contributors|length }} reviewer{{ contributors|pluralize }}</h3>
              <ul class="list-group remove-bottom-margin">
              {% for contributor in contributors %}
                  <li class="list-group-item">
                      <p class="bold">{{ contributor.get_full_name }} ({{contributor.reviewer.affiliation}})</p>
                      <p class="text-muted">
                          Group: {{ contributor.reviewer.group }}<br />
                          Workplace: {{ contributor.reviewer.workplace }}
                          {% if request.user.is_authenticated and request.user.reviewer.is_GEL %}
                              <br /><a href="mailto:{{ contributor.email }}" class="link-muted word-break">{{ contributor.email }}</a>
                          {% endif %}
                      </p>
                  </li>
              {% endfor %}
              </ul>
          {% endif %}
      </div>
  </div>

{% with entities=panel.get_all_entities_extra %}
  <h2 class="add-label-margin">{{ entities|length }} Entities</h2>
  <h3 class="text-muted normal remove-top-margin add-bottom-margin">{{ panel.stats.number_of_evaluated_entities }} reviewed{% if request.user.is_authenticated and request.user.reviewer.is_GEL %}, {{ panel.stats.number_of_ready_entities }} ready{% endif %}, {{ panel.stats.number_of_green_entities }} green</h3>

  <div data-module="sortable-table" data-default-key="entity">
      <div class="table-responsive" data-module="filterable-table">
          <table class="table table-bordered table-hover" id="entities_table">
            {% include "panels/entities_list_table.html" with is_super_panel=panel.is_super_panel %}
          </table>
      </div>
  </div>
{% endwith %}

  {% if panel.version_comment and panel.major_version %}
     <h2>Major version comments</h2>
      <ul class="list-group remove-bottom-margin">
          <li class="list-group-item">
              <p class="remove-bottom-margin">{{ panel.version_comment|linebreaksbr }}</p>
          </li>
      </ul>
  {% endif %}

  {% if not panel.is_super_panel and request.user.is_authenticated and request.user.reviewer.is_GEL %}
      <h3 class="add-top-margin">Promote to version {{ panel.major_version|add:"1" }}</h3>
      <div class="well">
          <p>Promoting a panel will:</p>
          <ul>
              <li>email all reviewers, thanking them for their contribution</li>
              <li>reset the "ready" flag on all genes</li>
              <li>increase the major version of the panel</li>
          </ul>
          <form action="{% url 'panels:promote' panel.panel.id %}" method="post" class="form add-top-margin">
              {% csrf_token %}
              <fieldset>
                  {% for field in promote_panel_form %}
                      <div class="form-group">
                          {% if field.errors %}
                              {% for error in field.errors %}
                                  <span class="label label-danger">{{ error|escape }}</span>
                              {% endfor %}
                          {% endif %}
                          {% bootstrap_field field %}
                      </div>
                  {% endfor %}
                  <input type="submit" class="btn btn-info" value="Increase Version">
              </fieldset>
          </form>
      </div>
  {% endif %}

  <h2>Downloads</h2>
  <div class="well">
    <h3 class="remove-top-margin">Download lists</h3>
    <ul>
      <li><a href="{% url 'panels:download_panel_tsv' panel.panel.id '01234' %}">Whole panel</a></li>
      <li><a href="{% url 'panels:download_panel_tsv' panel.panel.id '34' %}">Green list (high evidence)</a></li>
      <li><a href="{% url 'panels:download_panel_tsv' panel.panel.id '234' %}">Green and Amber Genes</a></li>
      <li><a href="{% url 'panels:download_panel_tsv' panel.panel.id '2' %}">Amber Genes</a></li>
      <li><a href="{% url 'panels:download_panel_tsv' panel.panel.id '01' %}">Red list (low evidence)</a></li>
    </ul>
    <h3>Download Version</h3>
      <div class="form-row">
          <div class="col">
            <div class="form-group">
            <div class="inline-group">
            <form class="form-inline" action="{% url 'panels:download_old_panel_tsv' panel.panel.id %}" method="post">
            {% csrf_token %}
            <input type="text" value="" placeholder="Panel version, for example 0.1", name="panel_version" class="input form-control">
              <button type="submit" class="btn btn-primary">Download</button></form>
            </div>
            </div>
        </div>
    {% if signed_off %}
    <div class="col">
        <div class="form-group">
          <div class="inline-group">
              <form class="form" action="{% url 'panels:download_old_panel_tsv' panel.panel.id %}" method="post">{% csrf_token %}
              <input type="hidden" value="{{ signed_off.major_version }}.{{ signed_off.minor_version }}" name="panel_version" class="input form-control">
              <button type="submit" class="btn btn-primary">Download Latest Signed-Off Version</button>
              </form>
          </div>
        </div>
    </div>
    {% endif %}
      </div>
  </div>
</div>
{% endblock %}